In [722]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [723]:
# Load libraries
import pandas as pd
import numpy as np
from google.colab import files
from sklearn import preprocessing
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import mean_absolute_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn import metrics 
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import callbacks
from tensorflow.keras.callbacks import ReduceLROnPlateau
from tensorflow.keras.optimizers import Adam
import tensorflow
from sklearn.ensemble import RandomForestClassifier
tensorflow.random.set_seed(0)
from numpy.random import seed
seed(1)

In [724]:
# Load training data
train_data = pd.read_csv('gdrive/MyDrive/train_internet.csv')
len(train_data)

965

In [725]:
train_data.head()

clientid_cr  ... conversion_fraud
0        75694  ...             True
1        75694  ...             True
2        75694  ...             True
3        75694  ...             True
4        30431  ...             True

[5 rows x 56 columns]

In [726]:
# Load testing data
test_data = pd.read_csv('gdrive/MyDrive/test_internet.csv')
len(test_data)

455

In [727]:
test_data.head()

record_id  clientid_cr  ... optimize_on_cr  bundleId_cr
0       1000        82122  ...            NaN          NaN
1       1001        75694  ...            NaN          NaN
2       1002        75694  ...            NaN          NaN
3       1003        30431  ...            NaN          NaN
4       1004        30431  ...            NaN          NaN

[5 rows x 56 columns]

In [728]:
# Get the number of missing data points per column
missing_values_count_train = train_data.isnull().sum()
print(missing_values_count_train)

clientid_cr                        0
clmbuserid_cr                      0
conversiontime_cr                  0
imprid_cr                          0
adslotdimid_cr                     0
algo_cr                           20
audiences_cr                     199
clickbid_cr                      296
geodimid_cr                        0
ip_cr                             20
itemcolumbiaid_cr                  0
itemid_cr                          0
position_cr                       20
pubclientid_cr                     0
refurl_cr                        125
siteId_cr                          0
templateid_cr                    107
goalid_cr                          0
time_cr                            0
adLogType_cr                       0
v_cr                               1
allAudiences_cr                   47
pricingtype_cr                     0
osId_cr                           21
browserId_cr                      21
cityId_cr                         20
stateId_cr                        20
m

In [729]:
# Get the number of missing data points per column
missing_values_count_test = test_data.isnull().sum()
print(missing_values_count_test)

record_id                          0
clientid_cr                        0
clmbuserid_cr                      0
conversiontime_cr                  0
imprid_cr                          0
adslotdimid_cr                     0
algo_cr                            0
audiences_cr                      86
clickbid_cr                      150
geodimid_cr                        0
ip_cr                              0
itemcolumbiaid_cr                  0
itemid_cr                          0
position_cr                        0
pubclientid_cr                     0
refurl_cr                         47
siteId_cr                          0
templateid_cr                     41
goalid_cr                          0
time_cr                            0
adLogType_cr                       0
v_cr                               0
allAudiences_cr                   23
pricingtype_cr                     0
osId_cr                            0
browserId_cr                       0
cityId_cr                          0
s

In [730]:
# Plot statistics
#print('clientid_cr: ', len(train_data['clientid_cr'].unique()))
#print('adslotdimid_cr: ', len(train_data['adslotdimid_cr'].unique()))
#print('algo_cr: ', len(train_data['algo_cr'].unique()))
#print('clickbid_cr: ', len(train_data['clickbid_cr'].unique()))
#print('geodimid_cr: ', len(train_data['geodimid_cr'].unique()))
#print('ip_cr: ', len(train_data['ip_cr'].unique()))
#print('itemcolumbiaid_cr: ', len(train_data['itemcolumbiaid_cr'].unique()))
#print('itemid_cr: ', len(train_data['itemid_cr'].unique()))
#print('position_cr: ', len(train_data['position_cr'].unique()))
#print('pubclientid_cr: ', len(train_data['pubclientid_cr'].unique()))
#print('siteId_cr: ', len(train_data['siteId_cr'].unique()))
#print('templateid_cr: ', len(train_data['templateid_cr'].unique()))
#print('goalid_cr: ', len(train_data['goalid_cr'].unique()))
#print('adLogType_cr: ', len(train_data['adLogType_cr'].unique()))
#print('v_cr: ', len(train_data['v_cr'].unique()))
#print('pricingtype_cr: ', len(train_data['pricingtype_cr'].unique()))
#print('osId_cr: ', len(train_data['osId_cr'].unique()))
#print('browserId_cr: ', len(train_data['browserId_cr'].unique()))
#print('cityId_cr: ', len(train_data['cityId_cr'].unique()))
#print('stateId_cr: ', len(train_data['stateId_cr'].unique()))
#print('modelDimId_cr: ', len(train_data['modelDimId_cr'].unique()))
#print('lookUpFrom_cr: ', len(train_data['lookUpFrom_cr'].unique()))
#print('connTypeDimId_cr: ', len(train_data['connTypeDimId_cr'].unique()))
#print('ispDimId_cr: ', len(train_data['ispDimId_cr'].unique()))
#print('countryDimId_cr: ', len(train_data['countryDimId_cr'].unique()))
#print('goalTypeId_cr: ', len(train_data['goalTypeId_cr'].unique()))
#print('impressionTimeInMillis_cr: ', len(train_data['impressionTimeInMillis_cr'].unique()))
#print('clickTimeInMillis_cr: ', len(train_data['clickTimeInMillis_cr'].unique()))
#print('osVerDimId_cr: ', len(train_data['osVerDimId_cr'].unique()))
#print('uuidSource_cr: ', len(train_data['uuidSource_cr'].unique()))
#print('geoGrpDimId_cr: ', len(train_data['geoGrpDimId_cr'].unique()))
#print('stateGrpDimId_cr: ', len(train_data['stateGrpDimId_cr'].unique()))
#print('cityGrpDimId_cr: ', len(train_data['cityGrpDimId_cr'].unique()))

In [731]:
train_imputed = train_data.fillna(method='bfill', axis=0).fillna(0)
train_imputed.head()

clientid_cr  ... conversion_fraud
0        75694  ...             True
1        75694  ...             True
2        75694  ...             True
3        75694  ...             True
4        30431  ...             True

[5 rows x 56 columns]

In [732]:
test_imputed = test_data.fillna(method='bfill', axis=0).fillna(0)
test_imputed.head()

record_id  clientid_cr  ... optimize_on_cr  bundleId_cr
0       1000        82122  ...           True   52696020.0
1       1001        75694  ...           True   52696020.0
2       1002        75694  ...           True   52696020.0
3       1003        30431  ...           True   52696020.0
4       1004        30431  ...           True   52696020.0

[5 rows x 56 columns]

In [733]:
train_imputed = train_data.fillna(method='bfill', axis=0).fillna(0)
test_imputed = test_data.fillna(method='bfill', axis=0).fillna(0)
'''
features_lab = ['clientid_cr', 'adslotdimid_cr', 'algo_cr', 'clickbid_cr', 'geodimid_cr', 'ip_cr', 'itemcolumbiaid_cr', 'itemid_cr', 'position_cr',
                'pubclientid_cr', 'siteId_cr', 'templateid_cr', 'goalid_cr', 'adLogType_cr', 'v_cr', 'pricingtype_cr', 'osId_cr', 'browserId_cr',
                'cityId_cr', 'stateId_cr', 'modelDimId_cr', 'lookUpFrom_cr', 'connTypeDimId_cr', 'ispDimId_cr', 'countryDimId_cr', 'goalTypeId_cr',
                'impressionTimeInMillis_cr', 'clickTimeInMillis_cr',  'osVerDimId_cr', '*uuidSource_cr', 'geoGrpDimId_cr', 'stateGrpDimId_cr',
                'cityGrpDimId_cr']'''
features_lab = [ 'clientid_cr','adslotdimid_cr', 'itemcolumbiaid_cr', 'pubclientid_cr',  'adLogType_cr',  'pricingtype_cr', 'cityId_cr',
                 'stateId_cr', 'ispDimId_cr', 'countryDimId_cr', 'goalTypeId_cr','impressionTimeInMillis_cr', 'clickTimeInMillis_cr',  
                'osVerDimId_cr', 'geoGrpDimId_cr', 'cityGrpDimId_cr']

label_encoder = LabelEncoder()
#y = train_imputed.pop('conversion_fraud')
records = test_imputed.pop('record_id')
y = train_imputed['conversion_fraud']
y = label_encoder.fit_transform(y)
#cur_feature = 'clientid_cr'
for cur_feature in features_lab:
  train_imputed[cur_feature] = label_encoder.fit_transform(train_imputed[cur_feature])
  #Set classes in test which don't exist in the encoder to -1
  test_imputed.loc[~test_imputed[cur_feature].isin(label_encoder.classes_),cur_feature] = -1    
  #Encode classes that exist in the encoder
  test_imputed.loc[test_imputed[cur_feature].isin(label_encoder.classes_),cur_feature] = label_encoder.transform(test_imputed[cur_feature][test_imputed[cur_feature].isin(label_encoder.classes_)])
train_imputed.head()
#train_imputed.columns

clientid_cr  ... conversion_fraud
0           36  ...             True
1           36  ...             True
2           36  ...             True
3           36  ...             True
4           19  ...             True

[5 rows x 56 columns]

In [734]:
train_imputed = train_imputed[features_lab]
train_imputed.head()

clientid_cr  adslotdimid_cr  ...  geoGrpDimId_cr  cityGrpDimId_cr
0           36              70  ...               0                2
1           36               4  ...               0                5
2           36              76  ...               0                2
3           36              70  ...               0                2
4           19             180  ...               0                5

[5 rows x 16 columns]

In [735]:
train_imputed = train_imputed.to_numpy()
print(train_imputed[0])

[ 36  70   3   4   1   1   2  10 120   0   0   1   1   2   0   2]


In [736]:
test_imputed = test_imputed[features_lab]
test_imputed = test_imputed.to_numpy()
print(test_imputed[0])

[45. 39. 10.  6.  0.  1.  0. 33. 93.  1.  0.  1.  1.  0.  1.  1.]


In [737]:
#Train-test split
train_X, val_X, train_y, val_y = train_test_split(train_imputed,y,random_state=1,test_size=0.2)
print(train_X[0])

[ 11 180  41   0   1   2   3  12   8   0   0   0   0   0   0   1]


In [738]:
model = RandomForestClassifier(n_estimators = 100, random_state=1)
model.fit(train_X,train_y)
val_preds = model.predict(val_X)
print("VALIDATION ACCURACY OF THE MODEL: ", metrics.accuracy_score(val_y, val_preds))
print("VALIDATION F1-SCORE OF THE MODEL: ",metrics.f1_score(val_y, val_preds, average='weighted'))

VALIDATION ACCURACY OF THE MODEL:  0.9533678756476683
VALIDATION F1-SCORE OF THE MODEL:  0.9506548331187706


In [739]:
test_preds = model.predict(test_imputed)

In [740]:
test_preds = test_preds.flatten()

In [741]:
# The lines below shows how to save predictions in format used for competition scoring.
output = pd.DataFrame({'record_id': test_data.record_id,
                       'conversion_fraud': test_preds})

output.head()
output.to_csv('submission_internet.csv', index=False)
files.download('submission_internet.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>